# Generated by Django 4.0.1 on 2022-03-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcard',
            name='img',
            field=models.ImageField(default='images.png', upload_to='image'),
        ),
    ]
